First Cookbook merge
genohm/slims-api pull request #25
Opened 2023-11-27 16:45 UTC by willimsbw

Small readme update, addition of cookbook folder and first example plugin

2023-11-29 17:58 UTC, stefanfroelicher-agilent requested changes
All good as already discussed but just the camel doc

2023-11-29 17:58 UTC, stefanfroelicher-agilent commented on cookbook/readme.md
> +utilizing the slimsgate api. It is not intended to replace the slims development manual, [Apache's camel documentation](https://camel.apache.org/components/4.0.x),
Here I think we should not put 4.0.x version of camel doc -> since we are still in 3.x 
https://camel.apache.org/components/3.14.x/index.html

2023-11-29 17:58 UTC, stefanfroelicher-agilent commented on cookbook/readme.md
> +     * [Netty](https://camel.apache.org/components/4.0.x/netty-component.html) (TCP connection plumbing, handled by camel)
here same as previous comment -> put the 3.x version of the doc (https://camel.apache.org/components/3.14.x/index.html)

2023-11-30 06:33 UTC, stefanfroelicher-agilent approved these changes
Sounds good like this

2023-11-30 14:27 UTC, willimsbw commented
@stefanfroelicher-agilent just added the cookbook's first plugin to settings.gradle and readme.md settings.gradle example -- you can view the new changes.

2023-12-05 08:53 UTC, stefanfroelicher-agilent approved these changes
Perfect for me

2023-12-11 15:55 UTC, stefanfroelicher-agilent approved these changes
it looks all good for me

2023-12-11 15:58 UTC, merged